#!/bin/bash -e

INFILE=$1
OUTFILE=$2
shift; shift

if [ "$INFILE" == "-" ]; then
    if [ "$OUTFILE" == "-" ]; then
        exit 1
    else
        command "$@" >$OUTFILE
    fi
else
    if [ "$OUTFILE" == "-" ]; then
        command "$@" <$INFILE
    else
        command "$@" <$INFILE >$OUTFILE
    fi
fi
