#!/bin/bash -e
i=0
for var in "$@"
do
    INPUT_HASH[i]=`gg-hash $var`
    valueopts+=( --value ${INPUT_HASH[i]}=$var )
    fileargs+=( @{GGHASH:${INPUT_HASH[i]}} )
    i=$((i + 1))
done
PROG_NAME=cat
IOWRAP_HASH="VkIXLi2AvcdLUIbAIYdr4IfjH5c.ikp.MZ4QNEELTWPY00000133"

gg-create-thunk \
    "${valueopts[@]}" \
    --executable ${IOWRAP_HASH}=iowrap \
    --output out \
    --placeholder out \
    ${IOWRAP_HASH} iowrap - out ${PROG_NAME} "${fileargs[@]}" 2>&1
